### ISSUE TITLE
managed-by label of service-monitor-cluster-network-addons-operator is wrong 

### ISSUE THREAD

**Issue by erkanerol** [kubevirt/cluster-network-addons-operator#1051]
**What happened**:

I installed OpenShift 4.10 and observed these labels on service-monitor-cluster-network-addons-operator object.

```
  labels:
    app.kubernetes.io/component: network
    app.kubernetes.io/managed-by: hco-operator
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: v4.10.0
    networkaddonsoperator.network.kubevirt.io/version: sha256_ce0e77c4ee5e28356c359578f7342a3d3690ac0373018605439549e1
    openshift.io/cluster-monitoring: ""
    prometheus.cnao.io: ""
```

**What you expected to happen**:
It must be `app.kubernetes.io/managed-by: cluster-network-addons-operator` 

**Environment**:
OpenShift 4.10
