### ISSUE TITLE
[release-v0.70.0]: missing assets/files

### ISSUE THREAD

**Issue by jbpratt** [kubevirt/cluster-network-addons-operator#1261]
**What happened**:
the `v0.70.0` release has no assets tied to it. The files in the release notes result in a 404. https://github.com/kubevirt/cluster-network-addons-operator/releases/tag/v0.70.0

```
❯ curl -L https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.70.0/namespace.yaml
Not Found
❯ curl -I -L https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.70.0/namespace.yaml
HTTP/2 404
...
```

**What you expected to happen**:
The files to be available like in `v0.69.0`

```
❯ curl -L https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.69.0/namespace.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-network-addons
  labels:
    name: cluster-network-addons
    openshift.io/cluster-monitoring: "true"
```
