### ISSUE TITLE
Fail to cluster-sync after cluster-sync in case dynamic-networks is deployed

### ISSUE THREAD

**Issue by oshoval** [kubevirt/cluster-network-addons-operator#1543]
**What happened**:
dynamic-networks-controller stuck on terminating forever (8m+)

**What you expected to happen**:
Should not fail to terminate / redeploy / delete

**How to reproduce it (as minimally and precisely as possible)**:

# Alternative 1:

Deploy latest rebased cnao
```
cluster-up
cluster-sync
oc create -f _out/cluster-network-addons/99.0.0/network-addons-config-example.cr.yaml
```

wait till it is done (you can change the TO or run few times)
`oc wait networkaddonsconfig cluster --for condition=Available --timeout=5s
`
Run `cluster-sync` again after the CR was created.
It hangs on deletion forever.
If you check the pods you will see that `dynamic-networks` is hanged.

# Alternative 2:
Deploy latest rebased cnao
```
cluster-up
cluster-sync
oc create -f _out/cluster-network-addons/99.0.0/network-addons-config-example.cr.yaml
```

wait till it is done (you can change the TO or run few times)
`oc wait networkaddonsconfig cluster --for condition=Available --timeout=5s
`
(until here same as alternative 1)

`oc edit networkaddonsconfig cluster
`
see inline
```
spec:
  imagePullPolicy: IfNotPresent <---- delete all the lines below this one, not including this one, in the same edit
  kubeMacPool: {} <--- Delete me
  kubeSecondaryDNS: {} <--- Delete me
  linuxBridge: {} <--- Delete me
  macvtap: {} <--- Delete me
  multus: {} <--- Delete me
  multusDynamicNetworks: {} <--- Delete me
  ovs: {} <--- Delete me
```

You will see the pod hangs terminating.
Didn't see anything interesting in the logs.

**Note**:
If you delete only multusDynamicNetworks during edit on alternative 2 it won't happen.
The delete need to be in the same edit at one go.

**Anything else we need to know?**:

It worked few days ago, before the latest multusDynamicNetworks bump IIRC.

Seems it happens also if you just delete the whole CR using `oc delete`.

**Environment**:
Kubevirtci 1.25 that CNAO has.
