### ISSUE TITLE
OVS-cni installation in OpenShift

### ISSUE THREAD

**Issue by ydguala** [kubevirt/cluster-network-addons-operator#1600]
**What happened**:
Using de Cluster Network Addons Operator (CNAO) to install open vSwitch cni / ovs-cni is not deploying the ovs-cni deployment pods in OpenShift 4.13

**What you expected to happen**:
ovs-cni installed

**How to reproduce it (as minimally and precisely as possible)**:
As per [procedure described here](https://github.com/kubevirt/cluster-network-addons-operator#open-vswitch),  adding an empty object 'ovs' on the specs of `cluster` object of type `NetworkAddonsConfig`) is not deploying the ovs-cni pods.

```yaml
apiVersion: networkaddonsoperator.network.kubevirt.io/v1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  ovs: {}
```

**Anything else we need to know?**:
WORKAROUND?
In OpenShift 4.13 with OpenShift Virtualization, the ovs-cni installation is managed by the hyperconverged cluster operator (HCO) in an annotation in the HyperConverged objects:
 
https://github.com/kubevirt/hyperconverged-cluster-operator/blob/main/docs/cluster-configuration.md#ovs-opt-in-annotation

```YAML
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    deployOVS: "true"
...
```
**Environment**:
