### ISSUE TITLE
MultusDynamicNetworks fails on containerd systems

### ISSUE THREAD

**Issue by KrystianMarek** [kubevirt/cluster-network-addons-operator#1846]
**What happened**:
The addons operator deployed as per [instruction](https://github.com/kubevirt/cluster-network-addons-operator/tree/52850e6e77e767411663c28bb7657fbf197148cd?tab=readme-ov-file#configuration)
with:
```yaml
apiVersion: networkaddonsoperator.network.kubevirt.io/v1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  multus: {}
  multusDynamicNetworks: {}
  linuxBridge: {}
  kubeMacPool: {}
  ovs: {}
  macvtap: {}
  kubeSecondaryDNS: {}
  kubevirtIpamController: {}
  imagePullPolicy: Always
```
By default deploys multus [crio dynamic network controller](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/main/manifests/crio-dynamic-networks-controller.yaml) 
Rendering the controller broken when deployed on a system with containerd. There is another manifest dedicated to containerd systems [this](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/main/manifests/dynamic-networks-controller.yaml). `NetworkAddonsConfig.spec.multusDynamicNetworks` does not allow any configuration, not even choosing the correct manifest. 

**What you expected to happen**:
multusDynamicNetworks works on systems with containerd

**How to reproduce it (as minimally and precisely as possible)**:
Deploy NetworkAddonsConfig mentioned above on a system with containerd, for example ubuntu. 

**Workaround**:
Disable `multusDynamicNetworks` by deploying 
```yaml
apiVersion: networkaddonsoperator.network.kubevirt.io/v1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  imagePullPolicy: IfNotPresent
  kubeMacPool: {}
  kubeSecondaryDNS: {}
  kubevirtIpamController: {}
  linuxBridge: {}
  macvtap: {}
  multus: {}
  ovs: {}
```
Deploy [dynamic-networks-controller](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/blob/main/manifests/dynamic-networks-controller.yaml) separately. Be mindful of namespaces. Cluster network addons operator deploys to `cluster-network-addons` namespace. 

**Environment**:
- KubeVirt version (use `virtctl version`): 1.3.0
- Kubernetes version (use `kubectl version`): v1.28.6
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
