### ISSUE TITLE
Basic documentation/blog-series about usage of shipped components

### ISSUE THREAD

**Issue by phoracek** [kubevirt/cluster-network-addons-operator#244]
We should present our components as a set which works well together to users and have a reference point to NetworkAttachmentDefinition specs etc. Let's think about doing a blog post series on kubevirt.io about it.

## Linux Bridge

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "br1",
          "vlan": 100,
          "ipam": {}
        },
        {
          "type": "tuning"
        }
      ]
    }'
```

## Open vSwitch

```yaml

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-conf
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/br1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "br1",
      "vlan": 100
    }'
```

### Default bridged network on all nodes

```yaml
```

### VLAN on specific node with static IP

```yaml
```
