### ISSUE TITLE
Specify Version of each Network Addons

### ISSUE THREAD

**Issue by MarkSpencerTan** [kubevirt/cluster-network-addons-operator#481]
**What happened**:

We'd like to be able to specify the version of each plugin that gets deployed with the cluster-network-addons-operator. Right now we have to use an older release to support an older version of NMState for example, but that will limit us in the version we can use for the other plugins (multus for example)

**What you expected to happen**:

Hopefully we're able to provide the version of each plugin in the yaml spec:

```yaml
apiVersion: networkaddonsoperator.network.kubevirt.io/v1alpha1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  multus: {} # will pull latest by default
  nmstate: v0.21.0
  imagePullPolicy: Always
```
