### ISSUE TITLE
quay.io/kubevirt/cni-default-plugins:v0.8.7 does not contain bridge/tuning binaries

### ISSUE THREAD

**Issue by erdii** [kubevirt/cluster-network-addons-operator#636]
**What happened**: The `linuxBridge` option did not deploy the `bridge` and `tuning` binaries into `/opt/cni/bin` and the `cnv-{bridge,tuning}` symlinks are broken as well.

**What you expected to happen**: To see the `bridge` and `tuning` binaries in `/opt/cni/bin`. 

**How to reproduce it (as minimally and precisely as possible)**:

Use this NetworkAddonsConfig with the latest cluster-network-addons-operator version (v0.42.2):
```yaml
apiVersion: networkaddonsoperator.network.kubevirt.io/v1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  imagePullPolicy: IfNotPresent
  multus: {}
  linuxBridge: {}
```

Then have a look into the kube-cni-linux-bridge-plugin-* pod logs and also run `ls -l /opt/cni/bin` on nodes with such pods

**Anything else we need to know?**: The root cause is that the quay.io/kubevirt/cni-default-plugins:v0.8.7 does not contain the bridge/tuning binaries. When using v0.8.6 aka `sha256:680ac8fd5eeab39c9a3c01479da344bdcaa43aa065d07ae00513b7bafa22fccf` everything is there as expected.

**Environment**:
Kubernetes: Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Single node cluster on fedora 33
